name: CI for Pull Requests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  Build_Stateless_solution:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build Stateless solution
      run: dotnet build Stateless.sln --configuration Release --no-restore
      
    - name: Test Stateless
      run: dotnet test --no-restore --no-build --configuration Release
      
    - name: Authenticate to GitHub Packages
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/teal-inc/index.json"
  
    - name: Pack Release version
      if: github.event_name == 'push'
      run: dotnet pack src\Stateless\Stateless.csproj --configuration Release
    - name: Publish Release version
      if: github.event_name == 'push'
      run: dotnet nuget push src\Stateless\bin\Release\*.nupkg --source "github"
